### ISSUE TITLE
Missing effects for Resilient debuff reduction

### ISSUE THREAD

**Issue by Darxo** [EmoUsedHM01/Sellswords-Updated#1]
![image](https://github.com/EmoUsedHM01/Sellswords-Updated/assets/2252464/16595544-5598-477a-8abb-59d79f2d15f6)

- The vanilla effect `withered_effect` is currently not affected by the 25% debuff reduction of Resilient.
- Since you decided to also have it affect the damage dealt by bleeding, I assume you forgot to do the same for the `spider_poison_effect` and `legend_redback_spider_poison_effect`.
- Many of those effects don't adjust the tooltip correctly (but you also posted that you are aware of that)

- - - - -

I don't actually play SSU. I was just very interested in your implementation of such an ambitious stat. And I thought while I was looking over your code I might aswell document my findings.

**Comment by EmoUsedHM01** [comment]
Just fixed this, thanks for the report
