### ISSUE TITLE
Overwhelm - Tooltip doesn't match implementation

### ISSUE THREAD

**Issue by OberKnirps** [EmoUsedHM01/Sellswords-Updated#2]
# Expected behavior:
- should stack 7 time
- should display stat reduction as `-10%*stack_count`
- max stat reduction of -70%
# Current behavior:
- stacks 10 times, see pic 1
- displays wrong stat reduction (-50%), see pic 1
- max stack reduction of -100%, see pic 2
![20240623003928_1](https://github.com/EmoUsedHM01/Sellswords-Updated/assets/8419078/9834358e-bdbf-41d4-b2dd-838cc67a1003)
![20240623003945_1](https://github.com/EmoUsedHM01/Sellswords-Updated/assets/8419078/6034c104-8c01-422a-8bdd-eba1d79e76e5)

**Comment by EmoUsedHM01** [comment]
Just fixed both issues, thanks for reporting
