### ISSUE TITLE
"Huge" trait is not reducing fatigue build up on orc weapons

### ISSUE THREAD

**Issue by KoltiraTheDragon** [EmoUsedHM01/Sellswords-Updated#3]
Huge trait is supposed to reduce additional fatigue buildup on large weapons (as per tooltip), yet it doesn't. Verified that in battle as well - Split Man on Mansplitter ax costs 20 fat, which is an usual fat cost for that skills without any reductions applied.
P.S. No PTR here, just in case

![image](https://github.com/user-attachments/assets/fae86b24-4812-4622-ac7e-a4d93f1d06dc)

**Comment by KoltiraTheDragon** [comment]
Seems to be the issue with newest MSU
With MSU 1.2.7 it works kind of fine. The only issue I found is that after loading the save fat costs reset back to 20. Simply unequipping the weapon and equipping it back fixes it (until the next load)

**Comment by BreakyZ** [comment]
they fixed it in msu
